# Generated by Django 3.0.5 on 2020-05-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_img', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=30)),
                ('sub_title', models.CharField(max_length=70)),
                ('body', models.TextField()),
            ],
        ),
    ]
