# Generated by Django 3.0.5 on 2020-05-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='timestamp',
            field=models.DateField(auto_now=True),
        ),
    ]
